### ISSUE TITLE
u should add "amongus imposte" enchantment 

### ISSUE THREAD

**Issue by minecraftfan424** [ZBLL-CUBER/UnderscoreEnchants#1]
it can kill a random player on the server but give hints in chat who kill u and if the person who get killed writes the the enchants user will die

add and i will happy

**Comment by ZBLL-CUBER** [comment]
This is unlikely to be added (since the enchantments should be small addons and not something of such size), but I may consider. For now the issue is closed I suppose.

**Comment by ZBLL-CUBER** [comment]
P.S. Next time please reference my support Discord to suggest features - https://discord.com/invite/bBge7bj3ra
